FROM nvidia/cuda:11.3.1-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y software-properties-common && \ 
    add-apt-repository ppa:deadsnakes/ppa -y && \ 
    apt update && \ 
    apt install -y python3.8 python3.8-venv git ffmpeg libsm6 libxext6

ENV VIRTUAL_ENV=/opt/venv
RUN python3.8 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 --extra-index-url https://download.pytorch.org/whl/cu113 && \
    pip install numpy opencv_python Pillow rmi-pytorch runx scikit_image scipy

RUN git clone https://github.com/YetAnotherSpieskowcy/FFNet.git

ENTRYPOINT bash
